steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "gcr.io/${PROJECT_ID}/${PROJECT_ID}-red", "." ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/${PROJECT_ID}/${PROJECT_ID}-red" ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
          "run",
          "deploy",
          "${PROJECT_ID}-red",
          "--image",
          "gcr.io/${PROJECT_ID}/${PROJECT_ID}-red",
          "--region",
          "us-central1",
          "--platform",
          "managed",
          "--allow-unauthenticated",
      ]
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m" , "cp" , "-r" , "-n" ,"gs://${PROJECT_ID}.appspot.com/*", "gs://${PROJECT_ID}-dev.appspot.com/"]
images:
  - "gcr.io/${PROJECT_ID}/${PROJECT_ID}-red"
options:
  logging: CLOUD_LOGGING_ONLY
  # TODO: Solicitar confirmacion de build y deploy de una nueva version.
  # TODO: Enviar correo donde se informa la actualizacion.
  # TODO: Notificar que el envio fallo.
  # TODO: Format all files "npx prettier --write ."
  # TODO: Add tests
